# Generated by Django 5.1.2 on 2024-10-24 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='mine/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('EY', 'EYE'), ('EA', 'EAR'), ('NO', 'NOSE'), ('MO', 'MOUTH'), ('LI', 'LIPS')], max_length=2)),
            ],
        ),
    ]
