# Generated by Django 5.1.2 on 2024-10-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myvarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
